apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscoursework2
  labels:
     app: devopscoursework2
     type: front-end
spec:
  template:
     metadata:
       name: devopscoursework2-pod
       labels: 
         app: devopscoursework2
         type: front-end
     spec:
         containers:
           - name: devopscoursework2
             image: "craiguk/devopscoursework2:1.0"
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
